{
    'name': "HR Hospital",
    'version': '16.0.1.0.0',
    'category': 'Human Resources',
    'summary': """Odoo test task""",
    'license': 'LGPL-3',
    'author': "Antonov Mike",
    'website': 'https://github.com/antonovmike',
    'depends': [
        'base', 'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/hospital_menu.xml',
        'views/diagnosis_view.xml',
        'views/doctor_view.xml',
        'views/doctor_history_view.xml',
        'views/doctor_schedule_view.xml',
        'views/patient_view.xml',
        'views/person_view.xml',
        'views/visits_view.xml',
        'data/disease_data.xml',
        'demo/demo.xml',
        'wizard/wizard_menu.xml',
        'wizard/personal_doctor_override_wizard_views.xml',
        'wizard/diseases_report_wizard_views.xml',
        'wizard/appointment_transfer_views.xml',
        'wizard/fill_week_wizard_views.xml',
    ],
    'demo': [],
    'images': [],
    'live_test_url': '',
    'price': 0,
    'currency': 'EUR',
    'support': '',
    'application': False,
    'installable': True,
    'auto_install': False,
}
