{
    'name': "HR Beauty salon",
    'version': '17.0.1.0.0',
    'category': 'Human Resources',
    'summary': """Demo Beauty salon module""",
    'license': 'LGPL-3',
    'author': "Antonov Mike",
    'website': 'https://github.com/antonovmike',
    'depends': [
        'base',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/users_view.xml',
    ],
    'demo': [],
    'images': [],
    'live_test_url': '',
    'price': 0,
    'currency': 'EUR',
    'support': '',
    'application': True,
    'installable': True,
    'auto_install': False,
}
